# Generated by Django 3.1.2 on 2021-08-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210808_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='address1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='address2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='post_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
