# Generated by Django 3.1.2 on 2021-08-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210809_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='image',
            field=models.ImageField(default='user/default.png', upload_to='user/'),
        ),
    ]
